app:
  build: .
  command: "bundle exec rails s -b 0.0.0.0"
  environment:
    - DATABASE_HOST=db
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=
    - DATABASE_NAME=postgres
    - REDIS_URL=redis://redis:6379
    - GEM_HOME=/bundle
    - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
  volumes:
    - .:/decidimbcn
  volumes_from:
    - bundle
  links:
    - db
    - redis
  ports:
    - "3000:3000"

sidekiq:
  image: decidimbcn_app
  command: bundle exec sidekiq
  environment:
    - DATABASE_HOST=db
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=
    - DATABASE_NAME=postgres
    - REDIS_URL=redis://redis:6379
    - GEM_HOME=/bundle
  volumes:
    - .:/decidimbcn
  volumes_from:
    - bundle
  links:
    - db
    - redis

bundle:
  image: ubuntu:15.04
  command: echo 'Nothing to do here'
  volumes:
    - /bundle

db:
  image: postgres
  volumes_from:
    - db_data

db_data:
  image: ubuntu:15.04
  command: echo 'Nothing to do here'
  volumes:
    - /var/lib/postgresql/data

redis:
  image: "redis"
  volumes:
    - /var/lib/redis:/data
