db:
  image: postgres

worker: &worker
  build: .
  command: rake jobs:work
  environment:
    - DATABASE_HOST=db
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=
    - DATABASE_NAME=postgres
  volumes:
    - .:/usr/src/app
  links:
    - db

web:
  <<: *worker
  command: puma -C config/puma.rb
  ports:
    - "3000:3000"
  expose:
    - 3000
