default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development: &development
  <<: *default
  database: barcelona_participa_development

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: barcelona_participa_test
