districts:
  1:
    name: "Ciutat Vella"
  2:
    name: "Eixample"
  3:
    name: "Sants Montjuïc"
  4:
    name: "Les Corts"
  5:
    name: "Sarrià - Sant Gervasi"
  6:
    name: "Gràcia"
  7:
    name: "Horta - Guinardó"
  8:
    name: "Nou Barris"
  9:
    name: "Sant Andreu"
  10:
    name: "Sant Martí"
